#
# File: trace_decoder.py
# Description: This script decodes the traces issued by the SystemC models and provides: the average time spent in the
#              different phases (comp, rdwr, wait) by tiles, the power and energy consumption, the E2E latency and throughput.
#
#              This is the DSE version of the script, to be used with the DSE scripts. The trace_decoder.py script can also be
#              found in the "models" folder. The DSE version provides support for memory size.
#              This version provides a single function TraceDecoder()
# Author: Quentin Dariol
# License: 3-clause BSD license, Copyright 2026 - Quentin Dariol, Ralf Stemmer, Sébastien Le Nours, Sébastien Pillement,
#          Kim Grüttner, Domenik Helms - IETR UMR CNRS 6164, Nantes Université & German Aerospace Center (DLR e. V.)
#

import sys
import copy
import statistics
from contextlib import redirect_stdout



def TraceDecoder(net_file, selected_power_mode = 'P', memorysizetab=[1024, 256, 256, 256, 256, 256, 256]):

    #######################################
    #######################################
    # Extracting info from out.csv file
    #######################################
    #######################################

    # If ITERATION_NB not set by user, get the iteration number directly from the trace.
    # Note: User-fixed ITERATION_NB is currently not implemented, can be done manually by setting ITERATION_NB below (uncomment)
    ITERATION_NB = 0
    TILE_NB = 7

    with open(net_file) as f:
        for line in f:
            tmp_line = line.replace('\n','').split(',')
            current_iteration = int(tmp_line[0])
            if current_iteration>ITERATION_NB:
                ITERATION_NB = current_iteration
    ITERATION_NB = ITERATION_NB+1
    # ~ ITERATION_NB = 1

    # Initialization of variables
    mb_in_scenario = [False for i in range (TILE_NB)] # Will be set True if MicroBlaze is active in the scenario
    mb_has_actors  = [False for i in range (TILE_NB)] # Will be set True if MicroBlaze has actors (in some scenarios tiles have 'empty' actors, with only communication channels that take time)
    mb_has_rdwrs   = [False for i in range (TILE_NB)]
    mb_has_waits   = [False for i in range (TILE_NB)]
    emptylist_startstop = [[],[]]
    mb_comp_markers_start=[[] for i in range (TILE_NB)]
    mb_rdwr_markers_start=[[] for i in range (TILE_NB)]
    mb_wait_markers_start=[[] for i in range (TILE_NB)]
    mb_comp_markers_stop =[[] for i in range (TILE_NB)]
    mb_rdwr_markers_stop =[[] for i in range (TILE_NB)]
    mb_wait_markers_stop =[[] for i in range (TILE_NB)]
    iteration_markers = []
    list_of_events = []
    for i in range (ITERATION_NB):
        iteration_markers.append(copy.deepcopy(emptylist_startstop))

    # Parse trace generated by simulation
    with open(net_file) as f:
        for line in f:
            # Preprocessing and iteration number identification
            tmp_line = line.replace('\n','').split(',')
            current_iteration = int(tmp_line[0])
            if(current_iteration < ITERATION_NB):  #or ((ITERATION_NB==1) and (current_iteration==CONSIDERED_ITERATION)):
                # Iteration start and stop
                if "ITERATION" in line:
                    if "START" in line:
                        iteration_markers[current_iteration][0]=int(tmp_line[3])
                    if "STOP" in line:
                        iteration_markers[current_iteration][1]=int(tmp_line[3])

                # MicroBlaze activity
                if "MB" in line:
                    mb_number = int(tmp_line[1].replace('MB',''))
                    mb_in_scenario[mb_number]=True
                    tmp = []
                    tmp.append(int(tmp_line[4]))
                    tmp.append(tmp_line[3])
                    list_of_events.append(int(tmp_line[4]))
                    if ('POLLING' in line) or ('WAITING' in line):   #Note: 'POLLING' marker is deprecated
                        # ~ mb_wait_markers[current_iteration][mb_number].append(tmp)
                        if "START" in line:
                            mb_wait_markers_start[mb_number].append(int(tmp_line[4]))
                        elif "STOP" in line:
                            mb_wait_markers_stop[mb_number].append(int(tmp_line[4]))
                    elif "COMM" in line:
                            # ~ mb_rdwr_markers[current_iteration][mb_number].append(tmp)
                        if "START" in line:
                            mb_rdwr_markers_start[mb_number].append(int(tmp_line[4]))
                        elif "STOP" in line:
                            mb_rdwr_markers_stop[mb_number].append(int(tmp_line[4]))
                    else:
                        # ~ mb_comp_markers[current_iteration][mb_number].append(tmp)
                        mb_has_actors[mb_number]=True
                        if "START" in line:
                            mb_comp_markers_start[mb_number].append(int(tmp_line[4]))
                        if "STOP" in line:
                            mb_comp_markers_stop[mb_number].append(int(tmp_line[4]))


    # INSTANT WAITING COMPLETION FIX:
    #   Sometimes the START and STOP time are equal for WAITING activity (the token is available and the tile skips the WAITING
    #   to proceed directly with the COMM). This must be patched before the trace evaluation.
    waiting_entries_to_delete = []
    for n in range (TILE_NB):
        if mb_in_scenario[n]:
            for i in range (len(mb_wait_markers_start[n])):
                if mb_wait_markers_start[n][i] == mb_wait_markers_stop[n][i]:
                    waiting_entries_to_delete.append((n,i))
    for element in reversed(waiting_entries_to_delete):
        mb_wait_markers_start[element[0]].pop(element[1])
        mb_wait_markers_stop[element[0]].pop(element[1])

    # Same with RDWR
    #   Read and Write delays can be equal to 0 when using ANALYTICAL MODEL ONLY - ANON mode (which sets COMM time to 0).
    rdwr_entries_to_delete = []
    for n in range (TILE_NB):
        if mb_in_scenario[n]:
            for i in range (len(mb_rdwr_markers_start[n])):
                if mb_rdwr_markers_start[n][i] == mb_rdwr_markers_stop[n][i]:
                    rdwr_entries_to_delete.append((n,i))
    for element in reversed(rdwr_entries_to_delete):
        mb_rdwr_markers_start[element[0]].pop(element[1])
        mb_rdwr_markers_stop[element[0]].pop(element[1])

    # CHECK IF MICROBLAZES ACTUALLY HAVE WAITS AND COMMS (AFTER REMOVAL OF DELAYS = 0)
    for n in range (TILE_NB):
        if mb_in_scenario[n]:
            if (len(mb_rdwr_markers_start[n]) != 0):
                mb_has_rdwrs[n] = True
            if (len(mb_wait_markers_start[n]) != 0):
                mb_has_waits[n] = True

    ### Sort all event markers
    list_of_events=sorted(list_of_events)
    ### Remove redundant markers
    list_of_events = list(dict.fromkeys(list_of_events))


    #######################################
    #######################################
    # RETURNING ESTIMATIONS
    #######################################
    #######################################
    # TODO: Just return the value instead of outputing to txt file that is then read (historical for trace_decoder, can and should be updated for DSE)
    with open('./tmp.txt', 'w') as f:
        with redirect_stdout(f):

            #######################################
            #######################################
            # EXECUTION TIME, E2E LATENCY AND THROUGHPUT
            #######################################
            #######################################

            # Info for user
            print (" ")
            print ("Note: All presented durations are in processor cycles (clock frequency = 100 MHz), power consumptions in W, energy in mJ. Computation, RdWr and waiting rates are in %\n")
            print ("Number of iterations in trace: ", ITERATION_NB)


            # Execution time, end to end latency and throughput
            execution_time = []
            e2e_latency = []
            total_execution_time = iteration_markers[ITERATION_NB-1][1]
            for i in range (ITERATION_NB):
                execution_time.append(iteration_markers[i][1]-iteration_markers[i][0])
                if (i>0):
                    e2e_latency.append(iteration_markers[i][1]-iteration_markers[i-1][1])

            avg_execution_time = statistics.mean(execution_time)

            print ("Average execution time: ", avg_execution_time)
            if (ITERATION_NB > 1):
                avg_e2e_latency = statistics.mean(e2e_latency)
                print ("Average end to end latency: ", avg_e2e_latency)
                PROCESSOR_FREQUENCY = 100000000 #100MHz in Hz
                # Throughput is defined as number of outputs per second
                # Throughput = 1s / ((E2E in processor cycles)*(Period of the processor clock))
                avg_throughput=1/(avg_e2e_latency*(1/PROCESSOR_FREQUENCY))
                print ("Average throughput: ", avg_throughput)



            #######################################
            #######################################
            # UTILIZATION RATES OF TILES
            #######################################
            #######################################

            mb_total_wait_time = [0. for k in range (TILE_NB)]
            mb_total_rdwr_time = [0. for k in range (TILE_NB)]
            mb_total_comp_time = [0. for k in range (TILE_NB)]
            avg_comp = 0
            avg_rdwr = 0
            avg_wait = 0

            TILE_NB_USED = 0
            for mb_number in range (TILE_NB):
                if mb_in_scenario[mb_number]:
                    TILE_NB_USED += 1

            # For every MicroBlaze present in scenario, we compute the total computation, read/write and wait time
            for n in range (TILE_NB):
                if mb_in_scenario[n]:
                    for j in range (len(mb_comp_markers_start[n])):
                        mb_total_comp_time[n] += mb_comp_markers_stop[n][j]-mb_comp_markers_start[n][j]
                    for j in range (len((mb_rdwr_markers_start[n]))):
                        mb_total_rdwr_time[n] += mb_rdwr_markers_stop[n][j]-mb_rdwr_markers_start[n][j]
                    for j in range (len((mb_wait_markers_start[n]))):
                        mb_total_wait_time[n] += mb_wait_markers_stop[n][j]-mb_wait_markers_start[n][j]

            for n in range (TILE_NB):
                if mb_in_scenario[n]:
                    # We obtain the comp., rdwr and wait rates per tiles.
                    mb_total_comp_time[n] = mb_total_comp_time[n]/total_execution_time
                    mb_total_wait_time[n] = mb_total_wait_time[n]/total_execution_time
                    mb_total_rdwr_time[n] = mb_total_rdwr_time[n]/total_execution_time
                    # Normalize for all tiles (some tiles finish before the simulation end which results to utilization < 100%)
                    if (mb_total_comp_time[n] + mb_total_wait_time[n] + mb_total_rdwr_time[n] < 1):
                        tmp_array1 = [mb_total_comp_time[n], mb_total_rdwr_time[n], mb_total_wait_time[n]]
                        tmp_array2 = [mb_total_comp_time[n], mb_total_rdwr_time[n], mb_total_wait_time[n]]
                        for element in tmp_array2:
                            element = (element - min(tmp_array1)) / (max(tmp_array1) - min(tmp_array1))
                        mb_total_comp_time[n] = tmp_array2[0]
                        mb_total_rdwr_time[n] = tmp_array2[1]
                        mb_total_wait_time[n] = tmp_array2[2]
                    # Compute average rates in regards to all tiles in scenario.
                    avg_comp += mb_total_comp_time[n]
                    avg_rdwr += mb_total_rdwr_time[n]
                    avg_wait += mb_total_wait_time[n]

            if TILE_NB_USED > 0:
                avg_comp = avg_comp/TILE_NB_USED*100
                avg_rdwr = avg_rdwr/TILE_NB_USED*100
                avg_wait = avg_wait/TILE_NB_USED*100

                print("Average computation rate per tile: " + str(avg_comp))
                print("Average RdWr transaction rate per tile: " + str(avg_rdwr))
                print("Average waiting (for tokens) rate per tile: " + str(avg_wait))
                print("Average communication rate (waiting+RdWr) per tile: " + str(avg_rdwr+avg_wait))



            #######################################
            #######################################
            # POWER ESTIMATION
            #######################################
            #######################################

            ## Generate list of MB power states

            ### State X  = MicroBlaze OFF, not used in this application
            ### State A  = MicroBlaze computing actor
            ### State C  = MicroBlaze in communications (RDWR)
            ### State P  = MicroBlaze in polling

            ### By default all OFF at all events
            list_of_mb_power_states = [['X' for i in range (TILE_NB)] for event in list_of_events]

            ct_w = [0 for i in range (TILE_NB)]
            ct_c = [0 for i in range (TILE_NB)]
            ct_a = [0 for i in range (TILE_NB)]

            found = False

            for n in range (TILE_NB):
                if (mb_in_scenario[n]):
                    for i in range (len(list_of_events)):
                        # WAITING
                        # If the marker in list of event matches the marker in mb_wait_marker, the MB is currently in wait mode.
                        if (mb_has_waits[n]):
                            # ~ print(n, ct_w[n])
                            if (list_of_events[i] == mb_wait_markers_start[n][ct_w[n]]):
                                list_of_mb_power_states[i][n] = 'P'
                                found = True
                            elif (list_of_events[i] > mb_wait_markers_start[n][ct_w[n]]):
                                while (ct_w[n] < len(mb_wait_markers_start[n])-1) \
                                and (list_of_events[i] > mb_wait_markers_start[n][ct_w[n]]):
                                    ct_w[n] += 1
                        # RDWR
                        if (mb_has_rdwrs[n]):
                            if ((list_of_events[i] == mb_rdwr_markers_start[n][ct_c[n]])):
                                list_of_mb_power_states[i][n] = 'C'
                                found = True
                            elif (list_of_events[i] > mb_rdwr_markers_start[n][ct_c[n]]):
                                while (ct_c[n] < len(mb_rdwr_markers_start[n])-1) \
                                and (list_of_events[i] > mb_rdwr_markers_start[n][ct_c[n]]):
                                    if (ct_c[n] < (len(mb_rdwr_markers_start[n])-1)):
                                        ct_c[n] += 1
                        # ACTOR
                        if (mb_has_actors[n]):
                            if ((list_of_events[i] == mb_comp_markers_start[n][ct_a[n]])):
                                list_of_mb_power_states[i][n] = 'A'
                                found = True
                            elif (list_of_events[i] > mb_comp_markers_start[n][ct_a[n]]):
                                while (ct_a[n] < len(mb_comp_markers_start[n])-1) \
                                and (list_of_events[i] > mb_comp_markers_start[n][ct_a[n]]):
                                    if (ct_a[n] < (len(mb_comp_markers_start[n])-1)):
                                        ct_a[n] += 1
                        # NOT FOUND
                        if (not(found)) and (i>0):
                            # If the tile has actually finished its workload for the specified number of iterations, go back to 'X'
                            if  (ct_w[n] == len(mb_wait_markers_start[n])-1) \
                            and (ct_c[n] == len(mb_rdwr_markers_start[n])-1) \
                            and (ct_a[n] == len(mb_comp_markers_start[n])-1):
                                list_of_mb_power_states[i][n] = 'X'
                            # Else it means that it didn't change state at this event
                            else:
                                list_of_mb_power_states[i][n] = list_of_mb_power_states[i-1][n]
                        found = False

            ########################################
            ########################################
            # REFINED POWER MODEL
            ########################################
            ########################################

            # Delta (dynamic consumption)
            # lambdas
            lambda_comp  =  1 # 1.953125  # 1.367 ; 1.940
            lambda_cg    = -1 # -1.953125   #-1.367 ; -1.940
            lambda_sm    =  1.09 # 2.121497844827586  # 1.485 ; 2.121
            lambda_static = 1 # 1.57596982
            # ptile
            p_tile_delta = 0.00011636
            # Commented because all other versions of the platform use the interrupt-based platform no matter what.
            # ~ p_tile_fix_pol = 0.031
            p_tile_fix =  0.031 #0.036
            # ~ p_tile_fix_cg = 0.1 #0.036
            # Fixed (static consumption)
            p_static_fix = 0.678 #1.010
            contribution_cg_static = 0.033

            def GetStaticConsumption(memorysizetab, mode):
                result = p_static_fix + len(memorysizetab)*p_tile_fix
                for n in range(len(memorysizetab)):
                    result += lambda_static*p_tile_delta*memorysizetab[n]
                if (mode == 'CG'):
                    result += contribution_cg_static
                return result

            def GetTileConsumption(memory):
                # ~ return p_tile_delta*memory
                # Not working, so here's another proposition. Use without the lambdas. Just use -1* if clock gating.
                # ~ return 3.26e-05*memory + 0.0497
                return 0.058 #0.058

            print("Tile number in platform: " + str(len(memorysizetab)) + " | Memory sizes: " + str(memorysizetab))
            # Interrupt-based + Clock gating
            if (selected_power_mode=='CG'):
                print("Clock gating power model used.")
                list_of_power = [GetStaticConsumption(memorysizetab, 'CG') for event in list_of_events]
                for j in range (len(list_of_events)):
                    sharedmem_power = 0
                    mbnb_accessing_sharedmem = 0
                    for mb in range (0,7):
                        if list_of_mb_power_states[j][mb] == 'A':
                            list_of_power[j] += lambda_comp*GetTileConsumption(memorysizetab[mb])
                        elif list_of_mb_power_states[j][mb] == 'C':
                            mbnb_accessing_sharedmem += 1
                            sharedmem_power += lambda_sm*GetTileConsumption(memorysizetab[mb])
                        elif list_of_mb_power_states[j][mb] == 'P':
                            list_of_power[j] += lambda_cg*GetTileConsumption(memorysizetab[mb])
                    # If shared mem is currently accessed, add average power consumption of MB accessing the memory
                    if mbnb_accessing_sharedmem != 0:
                        list_of_power[j] += sharedmem_power/mbnb_accessing_sharedmem

            else: # Polling mode
                print("Polling power model used.")
                list_of_power = [GetStaticConsumption(memorysizetab, 'P') for event in list_of_events]
                for j in range (len(list_of_events)):
                    sharedmem_power = 0
                    mbnb_accessing_sharedmem = 0
                    for mb in range (0,7):
                        if list_of_mb_power_states[j][mb] == 'A':
                            list_of_power[j] += GetTileConsumption(memorysizetab[mb])
                        elif list_of_mb_power_states[j][mb] == ('C' or 'P'):
                            mbnb_accessing_sharedmem += 1
                            sharedmem_power += GetTileConsumption(memorysizetab[mb])
                    if mbnb_accessing_sharedmem != 0:
                        list_of_power[j] += sharedmem_power/mbnb_accessing_sharedmem

            ## Processing total power consumption
            total_power = 0.
            for j in range (len(list_of_events)-1):
                total_power += list_of_power[j]*(list_of_events[j+1]-list_of_events[j])
            # If no event: the user wants to check the static consumption. Return the static consumption.
            if len(list_of_events) == 0:
                total_power = GetStaticConsumption(len(memorysizetab), selected_power_mode, platform)


            if total_execution_time > 0:
                # Note: modif 18.10.2024: We use now end to end latency instead of execution time to obtain energy
                # Old: total_power = total_power / total_execution_time
                #      total_energy = total_power*(avg_execution_time*(1/PROCESSOR_FREQUENCY))*1000
                total_power = total_power / total_execution_time
                total_energy = total_power*(avg_e2e_latency*(1/PROCESSOR_FREQUENCY))*1000 #*1000 to show in mJ instead of J
                print ("Total predicted power consumption: " + str(total_power))
                print ("Total predicted energy consumption: " + str(total_energy))
            else:
                print ("Total predicted power consumption: " + str(total_power))
